image: node:14-alpine, python:3.7-alpine3.9
# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/

stages:
  - build
  - test
  - setup
  - deploy
  
build:
  stage: build
  tags:
    - docker
  script:
    - cd server
    - npm install

install_dependencies:
  stage: setup
  script:
    - apk update && apk add git curl python3 py3-pip
    - pip3 install pandas regex scikit-learn pymongo Flask flask-cors
    - python3 -m pip install -U pip
    - pip3 install numpy

test:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    MONGODB_URI: "mongodb://mongo:27017/serverTestDB"
  script:
    - cd server
    - npm run ci-test

deploy:
  stage: deploy
  tags:
    - docker
  image: ruby:alpine
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  environment:
    name: production
    url: https://$HEROKU_APP_NAME.herokuapp.com/
  only:
    refs:
      - master
    variables:
      - $HEROKU_APP_NAME
      - $HEROKU_API_KEY
