GET http://localhost:3000/api/

###
GET http://localhost:3000/v1/users

###
GET http://localhost:3000/v1/recipes
###

GET http://localhost:3000/v1/users/recipes/all
Content-Type: application/json

{
    "userId": "6501b5d9fb9b4037e83bf95a"
}

###
DELETE http://localhost:3000/v1/recipes/deleteOne
Content-Type: application/json

{
    "userId": "6501b5d9fb9b4037e83bf95a",
    "recipeId": "6501b7304ac1406f819b125a"
}
###
DELETE http://localhost:3000/v1/recipes/deleteAllFromUser
Content-Type: application/json

{
    "userId": "6501b5d9fb9b4037e83bf95a"
}

###
POST http://127.0.0.1:3000/v1/users/create-recipe
Content-Type: application/json

{
        "userId": "6501bd917f18daad355b838c",
        "title": "Chimichurri Wings",
        "image": "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/465250.jpg?resize=300:*&output-format=jpg&output-quality=auto",
        "sectionsAndIngredients": {
            "Ingredients": [
                "asim large shallot, minced"
            ]
        },
        "servings": "for 4 servings",
        "description": "Try these herby, garlicky wings for game day or any day!",
        "steps": [
            "IALLIIn a large bowl, combine the shallot, garlic, jalapeño, and red wine vinegar. Let sit for about 10 minutes."
        ],
        "tags": [
            "zepei"
        ],
        "nutritionalInfo": [
            "Calories 468"
        ]
    }
###
PATCH  http://127.0.0.1:3000/recipe/6501bd917f18daad355b838c
Content-Type: application/json

{
   "ingredients": [
      "asim",
      "Ingredientjkbkjhj 2",
      "Ingredient 3"
   ],
   "steps": [
      "Step 1: Do something",
      "Step 2: Do something else"
   ],
   "serving": "4 servings",
   "description": "This is a sample recipe.",
   "tags": [
      "tag1",
      "tag2"
   ],
   "nutritionalInfo": [
      {
         "name": "Calories",
         "value": "250"
      },
      {
         "name": "Protein",
         "value": "15g"
      }
   ]
}

###

POST http://localhost:3000/v1/users/signup
Content-Type: application/json

{
    "username": "User1",
    "email": "validEmail@gmail.com",
    "password": "123",
    "name": "Bruh"
}

###
PUT http://127.0.0.1:3000/user/64fae07460d5ee1ec21a21ac
Content-Type: application/json

{
    "username": "asim",
    "email": "asim@gmail.com",
    "password": "123",
    "name": "Bruh"
}
