GET http://localhost:3000/api/

###
GET http://localhost:3000/v1/users

###

GET http://localhost:3000/v1/users/4eb6e7e7e9b7f4194e000001

###
GET http://localhost:3000/v1/recipes
###

GET http://localhost:3000/v1/recipes/selectOne
Content-Type: application/json

{
    "recipeId": "650304e62bf4f7c72945d630"
}

###

GET http://localhost:3000/v1/users/recipes/all
Content-Type: application/json

{
    "userId": "6502f864b4b79b57207b6af1"
}

###
DELETE http://localhost:3000/v1/recipes/deleteOne
Content-Type: application/json

{
    "userId": "4eb6e7e7e9b7f4194e000001",
    "recipeId": "65021cabdad7075d911e9166"
}
###
DELETE http://localhost:3000/v1/recipes/deleteAllFromUser
Content-Type: application/json

{
    "userId": "4eb6e7e7e9b7f4194e000001"
}

###
POST http://127.0.0.1:3000/v1/users/create-recipe
Content-Type: application/json

{
        "userId": "6502f864b4b79b57207b6af1",
        "title": "Chimichurri Wings",
        "image": "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/465250.jpg?resize=300:*&output-format=jpg&output-quality=auto",
        "sectionsAndIngredients": {
            "Ingredients": [
                "asim large shallot, minced"
            ]
        },
        "servings": "for 4 servings",
        "description": "Try these herby, garlicky wings for game day or any day!",
        "steps": [
            "IALLIIn a large bowl, combine the shallot, garlic, jalapeño, and red wine vinegar. Let sit for about 10 minutes."
        ],
        "tags": [
            "zepei"
        ],
        "nutritionalInfo": [
            "Calories 468"
        ]
    }
###
PATCH  http://127.0.0.1:3000/v1/users/edit-recipe/
Content-Type: application/json

{
    "recipeId": "6502f97ab4b79b57207b6b61",
    "userId": "6502f864b4b79b57207b6af1",
   "ingredients": [
      "asim",
      "Ingredientjkbkjhj 2",
      "Ingredient 3"
   ],
   "steps": [
      "Step 1: Do something",
      "Step 2: Do something else"
   ],
   "serving": "4 servings",
   "description": "This is a sample recipe.",
   "tags": [
      "tag1",
      "tag2"
   ],
   "nutritionalInfo": [
      {
         "name": "Calories",
         "value": "250"
      },
      {
         "name": "Protein",
         "value": "15g"
      }
   ]
}
###
PUT http://localhost:3000/v1/users/replace-recipe
Content-Type: application/json

{
    "recipeId": "6502db2ea2dda82921aafc7c",
    "userId": "4eb6e7e7e9b7f4194e000001",
   "ingredients": [
      "asim",
      "Ingredientjkbkjhj 2",
      "Ingredient 3"
   ],
   "steps": [
      "Step 1: Do something",
      "Step 2: Do something else"
   ],
   "serving": "4 servings",
   "description": "This is a sample recipe.",
   "tags": [
      "tag1",
      "tag2"
   ],
   "nutritionalInfo": [
      {
         "name": "Calories",
         "value": "250"
      },
      {
         "name": "Protein",
         "value": "15g"
      }
   ]
}
###

POST http://localhost:3000/v1/users/signup
Content-Type: application/json

{
    "username": "User1",
    "email": "validEmail@gmail.com",
    "password": "123",
    "name": "Bruh"
}

###
PATCH  http://127.0.0.1:3000/v1/users/edit-user/
Content-Type: application/json

{
    "userId": "6501e0a5e6ab49f7ec469953",
    "username": "Ali",
    "email": "asim@gmail.com",
    "password": "123",
    "name": "Bruh"
}
###
POST http://127.0.0.1:3000/v1/users/favorite-recipes/
Content-Type: application/json

{
    "userId": "6501d3bddaaa1baae9a3b383",
    "recipeId": "6501d80714eaa6d12f0c0df6"

}
###

GET  http://127.0.0.1:3000/v1/users/sign-in
Content-Type: application/json

{
    "email":"gusalmual@student.gu.se",
    "password": "Admin123"
}

###
GET http://127.0.0.1:3000/v1/recipes/tags

###
POST http://127.0.0.1:3000/v1/users/recipes/comment
Content-Type: application/json

{
    "userId": "4eb6e7e7e9b7f4194e000001" ,
    "recipeId": "6502db2ea2dda82921aafc7c",
    "comment": "I dont know what to comment, kool recipe"
}
###

PATCH http://localhost:3000/v1/users/650738e7466f3905233d9528/comments/65073c1dbe5827270e5af4c4
Content-Type: application/json

{
    "commentId": "650305f02bf4f7c72945d662",
    "comment":"PLES BE EDITED"
}
