name: Build Vue
on:
  push: 
    branches: 
      - master
jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Deploy-Vue
      uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
      with:
        username: 'Indomet'
        reponame: 'LetBroCOOK'
        token: ${{ secrets.GITHUB_TOKEN }}
        basebranchname: 'master'name: 'Deploy Vue Apps to Github Pages'
        description: 'This github action builds the vue app and creates a new branch names gh-pages to deploy the repo to github pages.'
        author: thefrustrateddev
        branding:
          icon: 'play'  
          color: 'green'
        inputs:
          username:
            description: 'Username'
            required: true
          reponame:
            description: 'Reponame'
            required: true
          token:
            description: 'Your Github token'
            required: true
          buildscript:
            description: 'Build script specified in package.json (By default takes build as the script).'
            required: false
            default: 'build'
          basebranchname:
            description: 'Base branch through which the gh pages should be created'
            required: false
            default: 'master'
          email:
            description: 'Email for git config'
            required: false
            default: 'action@example.com'
          name:
            description: 'Name for Git Config'
            required: false
            default: 'action'
          commitmessage:
            description: 'Commit message for creation of gh pages'
            required: false
            default: 'Create gh-pages'
        runs:
          using: "composite"
          steps:
              - name: Build Vue
                run: |
                      CONFIGFILE=vue.config.js
                      if [ ! -f "$CONFIGFILE" ]; then
                          echo "$CONFIGFILE does not exist."
                          echo "::error ::vue config file missing"
                          exit 1
                      fi
                      npm ci
                      npm run ${{ inputs.buildscript }}
                shell: bash
              - name: Create gh-pages
                run: |
                      cd dist
                      ln -s index.html 404.html
                      git config --global user.email "${{ inputs.email }}"
                      git config --global user.name "${{ inputs.name }}"
                      git init
                      git add .
                      git commit -m '${{ inputs.commitmessage }}'
                      git push -f https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git ${{ inputs.basebranchname }}:gh-pages
                shell: bash
        