name: Build Vue
on:
  push: 
    branches: 
      - master
jobs:
  build_deploy_vue:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    steps:
    - name: Change to client directory
      run: cd client

    - uses: actions/checkout@v2

    - id: Build-Deploy-Vue
      uses: thefrustrateddev/vue-deploy-github-pages@v1.0.0
      with:
        username: 'Indomet'
        reponame: 'LetBroCooK'
        token: ${{ secrets.GITHUB_TOKEN }}
        basebranchname: 'master'
